/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminNotificationsRouteImport } from './routes/_admin.notifications'
import { Route as AdminForbiddenRouteImport } from './routes/_admin.forbidden'
import { Route as AdminDashboardRouteImport } from './routes/_admin.dashboard'
import { Route as AdminSystemUsersRouteImport } from './routes/_admin.system.users'
import { Route as AdminSystemSettingsRouteImport } from './routes/_admin.system.settings'
import { Route as AdminSystemRolesRouteImport } from './routes/_admin.system.roles'
import { Route as AdminSystemMenusRouteImport } from './routes/_admin.system.menus'
import { Route as AdminSystemAuditLogsRouteImport } from './routes/_admin.system.audit-logs'
import { Route as AdminDemosTableRouteImport } from './routes/_admin.demos.table'
import { Route as AdminDemosFormRouteImport } from './routes/_admin.demos.form'
import { Route as AdminDemosChartsRouteImport } from './routes/_admin.demos.charts'
import { Route as AdminAccountSettingsRouteImport } from './routes/_admin.account.settings'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminForbiddenRoute = AdminForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemUsersRoute = AdminSystemUsersRouteImport.update({
  id: '/system/users',
  path: '/system/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemSettingsRoute = AdminSystemSettingsRouteImport.update({
  id: '/system/settings',
  path: '/system/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemRolesRoute = AdminSystemRolesRouteImport.update({
  id: '/system/roles',
  path: '/system/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemMenusRoute = AdminSystemMenusRouteImport.update({
  id: '/system/menus',
  path: '/system/menus',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemAuditLogsRoute = AdminSystemAuditLogsRouteImport.update({
  id: '/system/audit-logs',
  path: '/system/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDemosTableRoute = AdminDemosTableRouteImport.update({
  id: '/demos/table',
  path: '/demos/table',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDemosFormRoute = AdminDemosFormRouteImport.update({
  id: '/demos/form',
  path: '/demos/form',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDemosChartsRoute = AdminDemosChartsRouteImport.update({
  id: '/demos/charts',
  path: '/demos/charts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountSettingsRoute = AdminAccountSettingsRouteImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AdminDashboardRoute
  '/forbidden': typeof AdminForbiddenRoute
  '/notifications': typeof AdminNotificationsRoute
  '/account/settings': typeof AdminAccountSettingsRoute
  '/demos/charts': typeof AdminDemosChartsRoute
  '/demos/form': typeof AdminDemosFormRoute
  '/demos/table': typeof AdminDemosTableRoute
  '/system/audit-logs': typeof AdminSystemAuditLogsRoute
  '/system/menus': typeof AdminSystemMenusRoute
  '/system/roles': typeof AdminSystemRolesRoute
  '/system/settings': typeof AdminSystemSettingsRoute
  '/system/users': typeof AdminSystemUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AdminDashboardRoute
  '/forbidden': typeof AdminForbiddenRoute
  '/notifications': typeof AdminNotificationsRoute
  '/account/settings': typeof AdminAccountSettingsRoute
  '/demos/charts': typeof AdminDemosChartsRoute
  '/demos/form': typeof AdminDemosFormRoute
  '/demos/table': typeof AdminDemosTableRoute
  '/system/audit-logs': typeof AdminSystemAuditLogsRoute
  '/system/menus': typeof AdminSystemMenusRoute
  '/system/roles': typeof AdminSystemRolesRoute
  '/system/settings': typeof AdminSystemSettingsRoute
  '/system/users': typeof AdminSystemUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/forbidden': typeof AdminForbiddenRoute
  '/_admin/notifications': typeof AdminNotificationsRoute
  '/_admin/account/settings': typeof AdminAccountSettingsRoute
  '/_admin/demos/charts': typeof AdminDemosChartsRoute
  '/_admin/demos/form': typeof AdminDemosFormRoute
  '/_admin/demos/table': typeof AdminDemosTableRoute
  '/_admin/system/audit-logs': typeof AdminSystemAuditLogsRoute
  '/_admin/system/menus': typeof AdminSystemMenusRoute
  '/_admin/system/roles': typeof AdminSystemRolesRoute
  '/_admin/system/settings': typeof AdminSystemSettingsRoute
  '/_admin/system/users': typeof AdminSystemUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/forbidden'
    | '/notifications'
    | '/account/settings'
    | '/demos/charts'
    | '/demos/form'
    | '/demos/table'
    | '/system/audit-logs'
    | '/system/menus'
    | '/system/roles'
    | '/system/settings'
    | '/system/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/forbidden'
    | '/notifications'
    | '/account/settings'
    | '/demos/charts'
    | '/demos/form'
    | '/demos/table'
    | '/system/audit-logs'
    | '/system/menus'
    | '/system/roles'
    | '/system/settings'
    | '/system/users'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/_admin/dashboard'
    | '/_admin/forbidden'
    | '/_admin/notifications'
    | '/_admin/account/settings'
    | '/_admin/demos/charts'
    | '/_admin/demos/form'
    | '/_admin/demos/table'
    | '/_admin/system/audit-logs'
    | '/_admin/system/menus'
    | '/_admin/system/roles'
    | '/_admin/system/settings'
    | '/_admin/system/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/notifications': {
      id: '/_admin/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/forbidden': {
      id: '/_admin/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof AdminForbiddenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/system/users': {
      id: '/_admin/system/users'
      path: '/system/users'
      fullPath: '/system/users'
      preLoaderRoute: typeof AdminSystemUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/system/settings': {
      id: '/_admin/system/settings'
      path: '/system/settings'
      fullPath: '/system/settings'
      preLoaderRoute: typeof AdminSystemSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/system/roles': {
      id: '/_admin/system/roles'
      path: '/system/roles'
      fullPath: '/system/roles'
      preLoaderRoute: typeof AdminSystemRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/system/menus': {
      id: '/_admin/system/menus'
      path: '/system/menus'
      fullPath: '/system/menus'
      preLoaderRoute: typeof AdminSystemMenusRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/system/audit-logs': {
      id: '/_admin/system/audit-logs'
      path: '/system/audit-logs'
      fullPath: '/system/audit-logs'
      preLoaderRoute: typeof AdminSystemAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/demos/table': {
      id: '/_admin/demos/table'
      path: '/demos/table'
      fullPath: '/demos/table'
      preLoaderRoute: typeof AdminDemosTableRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/demos/form': {
      id: '/_admin/demos/form'
      path: '/demos/form'
      fullPath: '/demos/form'
      preLoaderRoute: typeof AdminDemosFormRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/demos/charts': {
      id: '/_admin/demos/charts'
      path: '/demos/charts'
      fullPath: '/demos/charts'
      preLoaderRoute: typeof AdminDemosChartsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/account/settings': {
      id: '/_admin/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AdminAccountSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminForbiddenRoute: typeof AdminForbiddenRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminAccountSettingsRoute: typeof AdminAccountSettingsRoute
  AdminDemosChartsRoute: typeof AdminDemosChartsRoute
  AdminDemosFormRoute: typeof AdminDemosFormRoute
  AdminDemosTableRoute: typeof AdminDemosTableRoute
  AdminSystemAuditLogsRoute: typeof AdminSystemAuditLogsRoute
  AdminSystemMenusRoute: typeof AdminSystemMenusRoute
  AdminSystemRolesRoute: typeof AdminSystemRolesRoute
  AdminSystemSettingsRoute: typeof AdminSystemSettingsRoute
  AdminSystemUsersRoute: typeof AdminSystemUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminForbiddenRoute: AdminForbiddenRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminAccountSettingsRoute: AdminAccountSettingsRoute,
  AdminDemosChartsRoute: AdminDemosChartsRoute,
  AdminDemosFormRoute: AdminDemosFormRoute,
  AdminDemosTableRoute: AdminDemosTableRoute,
  AdminSystemAuditLogsRoute: AdminSystemAuditLogsRoute,
  AdminSystemMenusRoute: AdminSystemMenusRoute,
  AdminSystemRolesRoute: AdminSystemRolesRoute,
  AdminSystemSettingsRoute: AdminSystemSettingsRoute,
  AdminSystemUsersRoute: AdminSystemUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
